import Head from 'next/head'
import Header from '../components/Header/Header'
import NavBar from '../components/NavBar/NavBar'


export default function Home() {
  return (
    <div >
      <Head>
        <title>«Խարույկ» արշավական ակումբ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fire.png" />
      </Head>
     <Header />
     <NavBar />
    </div>
  )
}
