import Head from 'next/head'
import Header from '../components/Header/Header'
import NavBar from '../components/NavBar/NavBar'
import SimpleImageSlider from "react-simple-image-slider";

const images = [
  { url: "/images/slide_1.jpg" },
  { url: "/images/slide_2.jpg" },
  { url: "/images/slide_3.jpg" },
  { url: "/images/slide_4.jpg" },
  { url: "/images/slide_5.jpg" },
];

const App = () => {
  return (
    <div>
      <SimpleImageSlider
        width={'100%'}
        height={'85vh'}
        images={images}
        showBullets={true}
        showNavs={true}
      />
    </div>
  );
}
export default function Home() {
  return (
    <div >
      <Head>
        <title>«Խարույկ» արշավական ակումբ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fire.png" />
      </Head>


     <Header />
     <NavBar />
     <App />

    </div>
  )
}
